name: flutter_skeleton_loader
description: Crea efectos de carga elegantes y personalizables en Flutter con soporte para widgets comunes mientras se cargan datos.
version: 1.1.0
homepage: https://github.com/idamkiller/flutter_skeleton_loader
repository: https://github.com/idamkiller/flutter_skeleton_loader
issue_tracker: https://github.com/idamkiller/flutter_skeleton_loader/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
