name: flutter_skeleton_loader
description: "Una biblioteca Flutter para crear efectos de carga (skeletons) elegantes y personalizables. Proporciona una forma sencilla de mostrar placeholders mientras se cargan los datos reales, con soporte para todos los widgets comunes de Flutter."
version: 1.0.0
homepage: https://github.com/idamkiller/flutter_skeleton_loader
repository: https://github.com/idamkiller/flutter_skeleton_loader
issue_tracker: https://github.com/idamkiller/flutter_skeleton_loader/issues
documentation: https://pub.dev/packages/flutter_skeleton_loader

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
